package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class Actor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.first_name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.last_name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actor
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.id
     *
     * @return the value of actor.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.id
     *
     * @param id the value for actor.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.first_name
     *
     * @return the value of actor.first_name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.first_name
     *
     * @param firstName the value for actor.first_name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.last_name
     *
     * @return the value of actor.last_name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.last_name
     *
     * @param lastName the value for actor.last_name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.last_update
     *
     * @return the value of actor.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.last_update
     *
     * @param lastUpdate the value for actor.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}