package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.ckey
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String ckey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cval
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String cval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table category
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.ckey
     *
     * @return the value of category.ckey
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getCkey() {
        return ckey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.ckey
     *
     * @param ckey the value for category.ckey
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setCkey(String ckey) {
        this.ckey = ckey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cval
     *
     * @return the value of category.cval
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getCval() {
        return cval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cval
     *
     * @param cval the value for category.cval
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setCval(String cval) {
        this.cval = cval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.last_update
     *
     * @return the value of category.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.last_update
     *
     * @param lastUpdate the value for category.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.remark
     *
     * @return the value of category.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.remark
     *
     * @param remark the value for category.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}