package cn.sh.sbl.hotel.beans;

import java.io.Serializable;

public class FileKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.film_id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.film_id
     *
     * @return the value of file.film_id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.film_id
     *
     * @param filmId the value for file.film_id
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }
}