package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class File extends FileKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_size
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.category_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Integer categoryFilm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_size
     *
     * @return the value of file.file_size
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_size
     *
     * @param fileSize the value for file.file_size
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.last_update
     *
     * @return the value of file.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.last_update
     *
     * @param lastUpdate the value for file.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.remark
     *
     * @return the value of file.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.remark
     *
     * @param remark the value for file.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.category_film
     *
     * @return the value of file.category_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Integer getCategoryFilm() {
        return categoryFilm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.category_film
     *
     * @param categoryFilm the value for file.category_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setCategoryFilm(Integer categoryFilm) {
        this.categoryFilm = categoryFilm;
    }
}