package cn.sh.sbl.hotel.beans;

import java.io.Serializable;

public class FilmGenreKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_genre.category_genre
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    private Integer categoryGenre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_genre.film_id
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    private String filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_genre.category_genre
     *
     * @return the value of film_genre.category_genre
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    public Integer getCategoryGenre() {
        return categoryGenre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_genre.category_genre
     *
     * @param categoryGenre the value for film_genre.category_genre
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    public void setCategoryGenre(Integer categoryGenre) {
        this.categoryGenre = categoryGenre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_genre.film_id
     *
     * @return the value of film_genre.film_id
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_genre.film_id
     *
     * @param filmId the value for film_genre.film_id
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }
}