package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class Film implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.title
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.ratings
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String ratings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.release_year
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Date releaseYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.country
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.length
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Short length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.remark
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.description
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.id
     *
     * @return the value of film.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.id
     *
     * @param id the value for film.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.title
     *
     * @return the value of film.title
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.title
     *
     * @param title the value for film.title
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.ratings
     *
     * @return the value of film.ratings
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getRatings() {
        return ratings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.ratings
     *
     * @param ratings the value for film.ratings
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setRatings(String ratings) {
        this.ratings = ratings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.release_year
     *
     * @return the value of film.release_year
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Date getReleaseYear() {
        return releaseYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.release_year
     *
     * @param releaseYear the value for film.release_year
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setReleaseYear(Date releaseYear) {
        this.releaseYear = releaseYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.country
     *
     * @return the value of film.country
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.country
     *
     * @param country the value for film.country
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.length
     *
     * @return the value of film.length
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Short getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.length
     *
     * @param length the value for film.length
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLength(Short length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.last_update
     *
     * @return the value of film.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.last_update
     *
     * @param lastUpdate the value for film.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.remark
     *
     * @return the value of film.remark
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.remark
     *
     * @param remark the value for film.remark
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.description
     *
     * @return the value of film.description
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.description
     *
     * @param description the value for film.description
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }
}