package cn.sh.sbl.hotel.beans;

import java.io.Serializable;

public class FilmActorKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_actor.actor_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer actorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_actor.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_actor.actor_id
     *
     * @return the value of film_actor.actor_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_actor.actor_id
     *
     * @param actorId the value for film_actor.actor_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_actor.film_id
     *
     * @return the value of film_actor.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_actor.film_id
     *
     * @param filmId the value for film_actor.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }
}