package cn.sh.sbl.hotel.beans;

import java.io.Serializable;

public class FilmDirectorKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_director.director_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer directorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film_director.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_director.director_id
     *
     * @return the value of film_director.director_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_director.director_id
     *
     * @param directorId the value for film_director.director_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setDirectorId(Integer directorId) {
        this.directorId = directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film_director.film_id
     *
     * @return the value of film_director.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film_director.film_id
     *
     * @param filmId the value for film_director.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }
}