package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class MenuFilm extends MenuFilmKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.display_order
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.icon
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.display_order
     *
     * @return the value of menu_film.display_order
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.display_order
     *
     * @param displayOrder the value for menu_film.display_order
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.icon
     *
     * @return the value of menu_film.icon
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.icon
     *
     * @param icon the value for menu_film.icon
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.last_update
     *
     * @return the value of menu_film.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.last_update
     *
     * @param lastUpdate the value for menu_film.last_update
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.remark
     *
     * @return the value of menu_film.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.remark
     *
     * @param remark the value for menu_film.remark
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}