package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class Menu implements Serializable {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.category_style
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer categoryStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.display_order
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.has_child
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Boolean hasChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.valid
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.level
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.focus_icon
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String focusIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.remark
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent
     *
     * @return the value of menu.parent
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent
     *
     * @param parent the value for menu.parent
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.category_style
     *
     * @return the value of menu.category_style
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getCategoryStyle() {
        return categoryStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.category_style
     *
     * @param categoryStyle the value for menu.category_style
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setCategoryStyle(Integer categoryStyle) {
        this.categoryStyle = categoryStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.display_order
     *
     * @return the value of menu.display_order
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.display_order
     *
     * @param displayOrder the value for menu.display_order
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.path
     *
     * @return the value of menu.path
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.path
     *
     * @param path the value for menu.path
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.has_child
     *
     * @return the value of menu.has_child
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Boolean getHasChild() {
        return hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.has_child
     *
     * @param hasChild the value for menu.has_child
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setHasChild(Boolean hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.valid
     *
     * @return the value of menu.valid
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.valid
     *
     * @param valid the value for menu.valid
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.level
     *
     * @return the value of menu.level
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.level
     *
     * @param level the value for menu.level
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.focus_icon
     *
     * @return the value of menu.focus_icon
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getFocusIcon() {
        return focusIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.focus_icon
     *
     * @param focusIcon the value for menu.focus_icon
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setFocusIcon(String focusIcon) {
        this.focusIcon = focusIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.last_update
     *
     * @return the value of menu.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.last_update
     *
     * @param lastUpdate the value for menu.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.remark
     *
     * @return the value of menu.remark
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.remark
     *
     * @param remark the value for menu.remark
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}