package cn.sh.sbl.hotel.beans;

import java.io.Serializable;
import java.util.Date;

public class MenuFilm extends MenuFilmKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.display_order
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Date lastUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.display_order
     *
     * @return the value of menu_film.display_order
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.display_order
     *
     * @param displayOrder the value for menu_film.display_order
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.last_update
     *
     * @return the value of menu_film.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.last_update
     *
     * @param lastUpdate the value for menu_film.last_update
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}