package cn.sh.sbl.hotel.beans;

import java.io.Serializable;

public class MenuFilmKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.menu_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_film.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private String filmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.menu_id
     *
     * @return the value of menu_film.menu_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.menu_id
     *
     * @param menuId the value for menu_film.menu_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_film.film_id
     *
     * @return the value of menu_film.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_film.film_id
     *
     * @param filmId the value for menu_film.film_id
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId;
    }
}