package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.Director;
import cn.sh.sbl.hotel.beans.DirectorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DirectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int countByExample(DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByExample(DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insert(Director record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insertSelective(Director record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    List<Director> selectByExample(DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    Director selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Director record, @Param("example") DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExample(@Param("record") Director record, @Param("example") DirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByPrimaryKeySelective(Director record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByPrimaryKey(Director record);
}