package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.File;
import cn.sh.sbl.hotel.beans.FileExample;
import cn.sh.sbl.hotel.beans.FileKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int countByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int deleteByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int deleteByPrimaryKey(FileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    List<File> selectByExample(FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    File selectByPrimaryKey(FileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByExampleSelective(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByExample(@Param("record") File record, @Param("example") FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByPrimaryKey(File record);
}