package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.FilmActorExample;
import cn.sh.sbl.hotel.beans.FilmActorKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int countByExample(FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int deleteByExample(FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int deleteByPrimaryKey(FilmActorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int insert(FilmActorKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int insertSelective(FilmActorKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    List<FilmActorKey> selectByExample(FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int updateByExampleSelective(@Param("record") FilmActorKey record, @Param("example") FilmActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_actor
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int updateByExample(@Param("record") FilmActorKey record, @Param("example") FilmActorExample example);
}