package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.Film;
import cn.sh.sbl.hotel.beans.FilmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int countByExample(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByExample(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insert(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insertSelective(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    List<Film> selectByExampleWithBLOBs(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    List<Film> selectByExample(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    Film selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Film record, @Param("example") FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") Film record, @Param("example") FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExample(@Param("record") Film record, @Param("example") FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByPrimaryKeySelective(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByPrimaryKey(Film record);
}