package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.FilmLanguageExample;
import cn.sh.sbl.hotel.beans.FilmLanguageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int countByExample(FilmLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByExample(FilmLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByPrimaryKey(FilmLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insert(FilmLanguageKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insertSelective(FilmLanguageKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    List<FilmLanguageKey> selectByExample(FilmLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") FilmLanguageKey record, @Param("example") FilmLanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_language
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExample(@Param("record") FilmLanguageKey record, @Param("example") FilmLanguageExample example);
}