package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.FilmGenreExample;
import cn.sh.sbl.hotel.beans.FilmGenreKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int countByExample(FilmGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByExample(FilmGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int deleteByPrimaryKey(FilmGenreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insert(FilmGenreKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int insertSelective(FilmGenreKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    List<FilmGenreKey> selectByExample(FilmGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") FilmGenreKey record, @Param("example") FilmGenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_genre
     *
     * @mbggenerated Mon Nov 25 17:20:39 CST 2013
     */
    int updateByExample(@Param("record") FilmGenreKey record, @Param("example") FilmGenreExample example);
}