package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.FilmDirectorExample;
import cn.sh.sbl.hotel.beans.FilmDirectorKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmDirectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int countByExample(FilmDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int deleteByExample(FilmDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int deleteByPrimaryKey(FilmDirectorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int insert(FilmDirectorKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int insertSelective(FilmDirectorKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    List<FilmDirectorKey> selectByExample(FilmDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int updateByExampleSelective(@Param("record") FilmDirectorKey record, @Param("example") FilmDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_director
     *
     * @mbggenerated Mon Nov 25 11:20:37 CST 2013
     */
    int updateByExample(@Param("record") FilmDirectorKey record, @Param("example") FilmDirectorExample example);
}