package cn.sh.sbl.hotel.dao;

import cn.sh.sbl.hotel.beans.MenuFilm;
import cn.sh.sbl.hotel.beans.MenuFilmExample;
import cn.sh.sbl.hotel.beans.MenuFilmKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuFilmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int countByExample(MenuFilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int deleteByExample(MenuFilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int deleteByPrimaryKey(MenuFilmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int insert(MenuFilm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int insertSelective(MenuFilm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    List<MenuFilm> selectByExample(MenuFilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    MenuFilm selectByPrimaryKey(MenuFilmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByExampleSelective(@Param("record") MenuFilm record, @Param("example") MenuFilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByExample(@Param("record") MenuFilm record, @Param("example") MenuFilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByPrimaryKeySelective(MenuFilm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_film
     *
     * @mbggenerated Tue Nov 26 19:47:14 CST 2013
     */
    int updateByPrimaryKey(MenuFilm record);
}